### ISSUE TITLE
Could not find module ‘Hos.Common.Types’

### ISSUE THREAD

**Issue by pxc3113** [tathougies/hos#2]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS E:\hos> cd src
PS E:\hos\src> ghci
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
Prelude> :l main.hs
[ 1 of 11] Compiling Data.IntervalMap ( Data\IntervalMap.hs, interpreted )
[ 2 of 11] Compiling Hos.Arch.Types   ( Hos\Arch\Types.hs, interpreted )
[ 3 of 11] Compiling Hos.CBits        ( Hos\CBits.hs, interpreted )
[ 4 of 11] Compiling Hos.Types        ( Hos\Types.hs, interpreted )

Hos\Types.hs:37:1: error:
    Could not find module ‘Hos.Common.Types’
    Use -v to see a list of the files searched for.
   |
37 | import Hos.Common.Types
   | ^^^^^^^^^^^^^^^^^^^^^^^
Failed, three modules loaded.
*Hos.CBits>

**Comment by tathougies** [comment]
Hello!

Hos doesn’t use GHC. It uses the JHC compiler and requires its own custom build scripts. As such, I’ve never put any work into getting it going under GHCi.

Modifying it to work with GHC is a massive undertaking owing to the complexity of GHCs runtime
